#!/bin/bash
# Script to run emacsclient, for use as value of the EDITOR environment var.
#
# This became necessary when I found it impossible to use a value of EDITOR
# that had a command with arguments (or at least, such a value of EDITOR
# didn't work for editing crontabs in macOS 10.13.6).
#
# Copyright 2024 Michael Hucka.
# License: MIT License – see file "LICENSE" in the project website.
# Website: https://github.com/mhucka/emacs-hacks

socket_file="$HOME/.ssh/server"
alt_editor="${ALTERNATE_EDITOR:-emacs -nw}"

eclient=emacsclient
if [ -x /Applications/Emacs/Emacs.app/Contents/MacOS/bin/emacsclient ]; then
    eclient=/Applications/Emacs/Emacs.app/Contents/MacOS/bin/emacsclient
elif [ -x /Applications/Emacs.app/Contents/MacOS/bin/emacsclient ]; then
    eclient=/Applications/Emacs.app/Contents/MacOS/bin/emacsclient
elif [ -e /opt/homebrew/bin/emacsclient ]; then
    eclient=$(readlink -f /opt/homebrew/bin/emacsclient)
fi

tramp=""
if [[ ${SSH_CONNECTION:+set} ]]; then
    host=$(hostname -f)
    # Not all remote hosts set SSH_CONNECTION. CentOS doesn't, but Ubuntu does.
    port=$(echo $SSH_CONNECTION | rev | cut -f1 -d' ')
    tramp="--tramp=/ssh:$host#$port:"
fi

$eclient -q $tramp --socket-name=${socket_file} --alternate-editor="$alt_editor" "$@"
(( emacsclient_successful = ! $? ))

if [[ ! $emacsclient_successful ]]; then
    emacs --no-splash --no-desktop -nw "$@"
fi
